# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItSMYLYVRw1uBYtTRKZ71uYHFdezm56O

Question 1
"""

print("Twinkle, twinkle, little star")
print("\tHow I wonder what you are")
print("\t\tUp above the world so high")
print("\t\tLike a diamond in the sky")
print("Twinkle, twinkle, little star")
print("\tHow I wonder what you are")

"""Question 2"""

import sys
print(sys.version)

"""Question 3"""

from datetime import datetime
print(datetime.now())

"""Question 4"""

import math as m

radius = float(input("Radius: "))
print(m.pi*radius*radius)

"""Question 5"""

fname=input('Enter First Name: ')
lname=input('Enter Last Name: ')
print(lname + ' ' + fname)

"""Question 6"""

num1=int(input("Enter Number1: "))
num2=int(input("Enter Number2: "))
print("Addition= ",num1+num2)